# Generated by Django 6.0.7 on 2026-08-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_shipped',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ordered'), (1, 'Shipped'), (2, 'Accepted')], default=0),
        ),
    ]
