# Generated by Django 6.0.7 on 2026-08-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_order_is_closed_remove_order_is_shipped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ordered'), (1, 'Shipped'), (2, 'Accepted'), (3, 'Declined')], default=0),
        ),
    ]
